version: "3.9"
   
services:
  db:
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    env_file:
      - ./env-postgresql.dev
    #volumes:
    #   - pgdata:/var/lib/postgresql/data


  web:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0
    volumes:
      - .:/testassigment_forecast
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./env.dev


#volumes:
#  pgdata: